<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'user_create' => [[], ['_controller' => 'App\\Controller\\UserController::create'], [], [['text', '/user/create']], [], [], []],
    'user_update' => [['id'], ['_controller' => 'App\\Controller\\UserController::update'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
    'App\Controller\UserController::create' => [[], ['_controller' => 'App\\Controller\\UserController::create'], [], [['text', '/user/create']], [], [], []],
    'App\Controller\UserController::update' => [['id'], ['_controller' => 'App\\Controller\\UserController::update'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
];
